<?php
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CashController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DailyReportController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\LeaveRequestController;
use App\Http\Controllers\LoanPayableController;
use App\Http\Controllers\PayableController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\PaymentInstrumentController;
use App\Http\Controllers\PrinterConfigController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PurchaseOrderController;
use App\Http\Controllers\ReceivableController;
use App\Http\Controllers\ReturnController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SaleExchangeController;
use App\Http\Controllers\SettingsBackupController;
use App\Http\Controllers\ShiftAssignmentController;
use App\Http\Controllers\ShiftController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\StoreProfileController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UserAccountController;
use Illuminate\Support\Facades\Route;

Route::get('/health', fn () => ['status' => 'ok', 'database' => config('database.default')]);
Route::post('/auth/login', [AuthController::class, 'login']);
Route::middleware('auth:sanctum')->group(function (): void {
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::get('/products', [ProductController::class, 'index'])->middleware('ability:pos:read');
    Route::post('/products', [ProductController::class, 'store'])->middleware('ability:master:write');
    Route::put('/products/{id}', [ProductController::class, 'update'])->middleware('ability:master:write');
    Route::post('/products/{id}/photo', [ProductController::class, 'uploadPhoto'])->middleware('ability:master:write');
    Route::get('/customers', CustomerController::class)->middleware('ability:pos:read');
    Route::post('/sales', SaleController::class)->middleware('ability:pos:write');
    Route::get('/sales', [SaleController::class, 'index'])->middleware('ability:pos:read');
    Route::post('/sales/{invoice}/exchange', SaleExchangeController::class)->middleware('ability:pos:write');
    Route::get('/payment-methods', [PaymentMethodController::class, 'index'])->middleware('ability:pos:read');
    Route::get('/reports/daily', DailyReportController::class)->middleware('ability:pos:read');
    Route::get('/hrd/employees', EmployeeController::class)->middleware('ability:hrd:read');
    Route::get('/hrd/shifts', ShiftController::class)->middleware('ability:hrd:read');
    Route::get('/hrd/shift-assignments', [ShiftAssignmentController::class, 'index'])->middleware('ability:hrd:read');
    Route::post('/hrd/shift-assignments', [ShiftAssignmentController::class, 'store'])->middleware('ability:hrd:write');
    Route::get('/hrd/attendance', [AttendanceController::class, 'index'])->middleware('ability:hrd:read');
    Route::post('/hrd/attendance', [AttendanceController::class, 'store'])->middleware('ability:hrd:write');
    Route::get('/hrd/leave-requests', [LeaveRequestController::class, 'index'])->middleware('ability:hrd:read');
    Route::post('/hrd/leave-requests', [LeaveRequestController::class, 'store'])->middleware('ability:hrd:write');
    Route::put('/hrd/leave-requests/{id}/status', [LeaveRequestController::class, 'updateStatus'])->middleware('ability:hrd:write');

    Route::get('/suppliers', [SupplierController::class, 'index'])->middleware('ability:inventory:read');
    Route::post('/suppliers', [SupplierController::class, 'store'])->middleware('ability:inventory:write');
    Route::put('/suppliers/{id}', [SupplierController::class, 'update'])->middleware('ability:inventory:write');
    Route::get('/purchase-orders', [PurchaseOrderController::class, 'index'])->middleware('ability:inventory:read');
    Route::post('/purchase-orders', [PurchaseOrderController::class, 'store'])->middleware('ability:inventory:write');
    Route::put('/purchase-orders/{id}', [PurchaseOrderController::class, 'update'])->middleware('ability:inventory:write');
    Route::post('/purchase-orders/{poId}/receive', [PurchaseOrderController::class, 'receive'])->middleware('ability:inventory:write');
    Route::post('/returns', ReturnController::class)->middleware('ability:inventory:write');
    Route::get('/stock-movements', [StockController::class, 'movements'])->middleware('ability:inventory:read');
    Route::post('/stock-adjustments', [StockController::class, 'adjust'])->middleware('ability:inventory:write');

    Route::get('/settings/store-profile', [StoreProfileController::class, 'show'])->middleware('ability:settings:read');
    Route::put('/settings/store-profile', [StoreProfileController::class, 'update'])->middleware('ability:settings:write');
    Route::get('/settings/users', [UserAccountController::class, 'index'])->middleware('ability:settings:read');
    Route::post('/settings/users', [UserAccountController::class, 'store'])->middleware('ability:settings:write');
    Route::put('/settings/users/{id}', [UserAccountController::class, 'update'])->middleware('ability:settings:write');
    Route::get('/settings/role-permissions', [RolePermissionController::class, 'show'])->middleware('ability:settings:read');
    Route::put('/settings/role-permissions', [RolePermissionController::class, 'update'])->middleware('ability:settings:write');
    Route::get('/settings/printer', [PrinterConfigController::class, 'show'])->middleware('ability:settings:read');
    Route::put('/settings/printer', [PrinterConfigController::class, 'update'])->middleware('ability:settings:write');
    Route::post('/settings/printer/test-print', [PrinterConfigController::class, 'testPrint'])->middleware('ability:settings:write');
    Route::get('/settings/payment-methods', [PaymentMethodController::class, 'adminIndex'])->middleware('ability:settings:read');
    Route::post('/settings/payment-methods', [PaymentMethodController::class, 'store'])->middleware('ability:settings:write');
    Route::put('/settings/payment-methods/{id}', [PaymentMethodController::class, 'update'])->middleware('ability:settings:write');
    Route::delete('/settings/payment-methods/{id}', [PaymentMethodController::class, 'destroy'])->middleware('ability:settings:write');
    Route::get('/settings/audit-log', AuditLogController::class)->middleware('ability:settings:read');
    Route::post('/settings/backup', SettingsBackupController::class)->middleware('ability:settings:write');

    Route::get('/finance/cash-entries', [CashController::class, 'index'])->middleware('ability:finance:read');
    Route::post('/finance/cash-entries', [CashController::class, 'store'])->middleware('ability:finance:write');
    Route::get('/finance/payables', [PayableController::class, 'index'])->middleware('ability:finance:read');
    Route::post('/finance/payables/{id}/payments', [PayableController::class, 'addPayment'])->middleware('ability:finance:write');
    Route::get('/finance/loan-payables', [LoanPayableController::class, 'index'])->middleware('ability:finance:read');
    Route::post('/finance/loan-payables/{id}/payments', [LoanPayableController::class, 'addPayment'])->middleware('ability:finance:write');
    Route::get('/finance/receivables', [ReceivableController::class, 'index'])->middleware('ability:finance:read');
    Route::post('/finance/receivables', [ReceivableController::class, 'store'])->middleware('ability:finance:write');
    Route::post('/finance/receivables/{id}/payments', [ReceivableController::class, 'addPayment'])->middleware('ability:finance:write');
    Route::get('/finance/instruments', [PaymentInstrumentController::class, 'index'])->middleware('ability:finance:read');
    Route::post('/finance/instruments', [PaymentInstrumentController::class, 'store'])->middleware('ability:finance:write');
    Route::put('/finance/instruments/{id}/status', [PaymentInstrumentController::class, 'updateStatus'])->middleware('ability:finance:write');
});
