import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { ArchiveRestore, Banknote, Check, ChevronDown, CircleUserRound, Clock3, Minus, PackageSearch, Pause, Plus, Printer, Search, ShoppingBasket, Trash2, X } from 'lucide-react';
import { completeSale, getStoreProfile, listCustomers, listProducts } from '../lib/api';
import { money, number } from '../lib/money';
import { printReceipt } from '../lib/print';
import { submitCheckout } from '../lib/checkout';
import type { CartLine, Customer, HeldSale, Product, Unit } from '../types';

const STORAGE_KEY = 'sid-held-sales';
const general: Customer = { id: 'general', code: 'UMUM', name: 'Pelanggan Umum', tier: 'retail' };

export function Pos({ online }: { online: boolean }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<Product[]>([]); const [searchLoading,setSearchLoading]=useState(false); const [searchError,setSearchError]=useState(''); const [searchRetry,setSearchRetry]=useState(0); const [cart, setCart] = useState<CartLine[]>([]); const [customer, setCustomer] = useState<Customer>(general); const [dialog, setDialog] = useState<'unit'|'customer'|'payment'|'held'|null>(null); const [selected, setSelected] = useState(0); const [held, setHeld] = useState<HeldSale[]>(() => JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]')); const [notice, setNotice] = useState(''); const searchRef = useRef<HTMLInputElement>(null);
  const subtotal = useMemo(() => cart.reduce((sum, line) => sum + line.qty * line.unit.price, 0), [cart]); const discount = useMemo(() => cart.reduce((sum, line) => sum + line.discount, 0), [cart]); const total = subtotal - discount;
  // Barang stok habis/minus disaring di sini, sebelum masuk ke daftar hasil pencarian
  // maupun jalur pickSearch() exact-match - jadi kasir gak bisa nambahin barang yang
  // stoknya gak cukup sama sekali, bukan cuma ditolak belakangan pas bayar.
  useEffect(() => { let active=true; setSearchLoading(true); setSearchError(''); const timer = setTimeout(() => listProducts(query).then(data=>{if(active)setResults(data.filter(p=>p.stock>0))}).catch(error=>{if(active){setResults([]);setSearchError(error instanceof Error?error.message:'Pencarian barang gagal')}}).finally(()=>{if(active)setSearchLoading(false)}), 100); return () => { active=false; clearTimeout(timer); }; }, [query,searchRetry]);
  const add = useCallback((product: Product, unit = product.units[0]) => { setCart(current => { const i = current.findIndex(line => line.product.id === product.id && line.unit.name === unit.name); if (i < 0) return [...current, { product, unit, qty: 1, discount: 0 }]; return current.map((line, index) => index === i ? { ...line, qty: line.qty + 1 } : line); }); setQuery(''); searchRef.current?.focus(); }, []);
  const holdSale = useCallback(() => { if (!cart.length) return setNotice('Keranjang masih kosong.'); const sale: HeldSale = { id: crypto.randomUUID(), reference: `HOLD-${String(held.length + 1).padStart(3,'0')}`, customer, lines: cart, heldAt: new Date().toISOString() }; const next = [...held, sale]; setHeld(next); localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); setCart([]); setCustomer(general); setNotice(`${sale.reference} berhasil ditahan di perangkat ini.`); }, [cart, customer, held]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.ctrlKey || event.altKey || event.metaKey) return; if (event.key === 'Escape') { setDialog(null); return; } if (dialog) return; if (event.key === 'F1') { event.preventDefault(); if (cart.length) { setSelected(Math.max(0, cart.length - 1)); setDialog('unit'); } } if (event.key === 'F2') { event.preventDefault(); searchRef.current?.focus(); } if (event.key === 'F4') { event.preventDefault(); setDialog('customer'); } if (event.key === 'F5') { event.preventDefault(); holdSale(); } if (event.key === 'F8') { event.preventDefault(); if (cart.length && online) setDialog('payment'); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [cart.length, holdSale, online, dialog]);
  function pickSearch() { const exact = results.find(p => p.barcode === query || p.code.toLowerCase() === query.toLowerCase()); if (exact) add(exact); else if (results.length === 1) add(results[0]); }
  return <div className="pos-page"><div className="pos-header"><div><p className="eyebrow">Transaksi</p><h1>Penjualan kasir</h1></div><div className="invoice-draft"><span>Draft baru</span><strong>{new Date().toLocaleTimeString('id-ID', {hour:'2-digit',minute:'2-digit'})}</strong></div></div>
    {notice && <div className="notice info" role="status">{notice}<button className="icon-button" onClick={() => setNotice('')} aria-label="Tutup pesan"><X /></button></div>}
    <div className="pos-layout"><section className="pos-main"><div className="scan-row"><label className="scan-input"><Search aria-hidden="true"/><span className="sr-only">Scan barcode atau cari barang</span><input ref={searchRef} value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && pickSearch()} placeholder="Scan barcode atau cari barang…" autoFocus /></label><span className="key-hint">F2</span></div>
      {query && <div className="search-results" role="listbox" aria-label="Hasil pencarian">{searchLoading?<div className="empty-compact" role="status">Mencari barang…</div>:searchError?<div className="inline-recovery" role="alert"><span>{searchError}</span><button className="button secondary" onClick={()=>setSearchRetry(value=>value+1)}>Coba lagi</button></div>:<>{results.slice(0,6).map(product => <button key={product.id} role="option" aria-selected="false" onClick={() => add(product)}><div><strong>{product.name}</strong><span>{product.code} · {product.barcode}</span></div><div><strong>{money.format(product.units[0].price)}</strong><span>Stok {number.format(product.stock)}</span></div></button>)}{!results.length && <div className="empty-compact">Barang tidak ditemukan</div>}</>}</div>}
      <div className="cart-heading"><div><h2>Daftar belanja</h2><span>{cart.length} baris</span></div><button className="button ghost" disabled={!cart.length} onClick={() => setCart([])}><Trash2 /> Kosongkan</button></div>
      {!cart.length ? <div className="cart-empty"><ShoppingBasket /><h2>Belum ada barang</h2><p>Scan barcode atau cari nama barang untuk memulai.</p></div> : <div className="cart-list">{cart.map((line, index) => <article className="cart-line" key={`${line.product.id}-${line.unit.name}`} onClick={() => setSelected(index)} data-selected={selected === index}><div className="line-index">{index + 1}</div><div className="line-product"><strong>{line.product.name}</strong><span>{line.product.code}</span></div><button className="unit-select" onClick={() => { setSelected(index); setDialog('unit'); }}>{line.unit.name}<ChevronDown /></button><div className="qty-control"><button onClick={() => setCart(c => c.map((x,i) => i === index ? {...x, qty: Math.max(1,x.qty-1)} : x))} aria-label={`Kurangi ${line.product.name}`}><Minus /></button><span>{line.qty}</span><button onClick={() => setCart(c => c.map((x,i) => i === index ? {...x, qty:x.qty+1} : x))} aria-label={`Tambah ${line.product.name}`}><Plus /></button></div><div className="line-price"><span>{money.format(line.unit.price)}</span><strong>{money.format(line.qty * line.unit.price - line.discount)}</strong></div><button className="icon-button danger" onClick={() => setCart(c => c.filter((_,i) => i !== index))} aria-label={`Hapus ${line.product.name}`}><Trash2 /></button></article>)}</div>}
    </section><aside className="checkout-panel"><button className="customer-card" onClick={() => setDialog('customer')}><CircleUserRound /><span><small>Pelanggan</small><strong>{customer.name}</strong><em>{customer.code}</em></span><ChevronDown /></button><div className="summary"><div><span>Subtotal</span><strong>{money.format(subtotal)}</strong></div><div><span>Diskon</span><strong>- {money.format(discount)}</strong></div><div className="grand-total"><span>Total</span><strong>{money.format(total)}</strong></div></div><div className="checkout-actions"><button className="button secondary tall" onClick={holdSale} disabled={!cart.length}><Pause /> Tahan <kbd>F5</kbd></button><button className="button secondary tall" onClick={() => setDialog('held')}><ArchiveRestore /> Buka hold <span className="count">{held.length}</span></button><button className="button primary payment" disabled={!cart.length || !online} onClick={() => setDialog('payment')}><Banknote /><span>Bayar sekarang<small>{online ? 'Tunai / pembayaran lain' : 'Tidak tersedia saat offline'}</small></span><kbd>F8</kbd></button></div><div className="shortcut-strip"><span><kbd>F1</kbd> Satuan</span><span><kbd>F4</kbd> Pelanggan</span><span><kbd>Esc</kbd> Tutup</span></div></aside></div>
    {dialog === 'unit' && cart[selected] && <UnitDialog line={cart[selected]} onClose={() => setDialog(null)} onPick={unit => { setCart(c => c.map((line,i) => i === selected ? {...line,unit} : line)); setDialog(null); }} />}
    {dialog === 'customer' && <CustomerDialog onClose={() => setDialog(null)} onPick={value => { setCustomer(value); setDialog(null); }} />}
    {dialog === 'payment' && <PaymentDialog customer={customer} cart={cart} total={total} onClose={() => setDialog(null)} onDone={(invoice, printFailed) => { setCart([]); setCustomer(general); setDialog(null); setNotice(printFailed ? `Transaksi ${invoice} tersimpan, tetapi cetak gagal. Gunakan riwayat untuk cetak ulang.` : `Transaksi ${invoice} berhasil disimpan dan struk dikirim.`); }} />}
    {dialog === 'held' && <HeldDialog sales={held} onClose={() => setDialog(null)} onPick={sale => { setCart(sale.lines); setCustomer(sale.customer); const next = held.filter(x => x.id !== sale.id); setHeld(next); localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); setDialog(null); }} />}
  </div>;
}

function Modal({ title, children, onClose }: { title:string; children:ReactNode; onClose:()=>void }) { const ref=useRef<HTMLElement>(null); const previous=useRef<HTMLElement|null>(null); useEffect(()=>{previous.current=document.activeElement as HTMLElement; const box=ref.current; const focusable=()=>Array.from(box?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])')??[]); (box?.querySelector<HTMLElement>('[data-autofocus]')??focusable()[0])?.focus(); const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const all=focusable();if(!all.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};box?.addEventListener('keydown',trap);return()=>{box?.removeEventListener('keydown',trap);previous.current?.focus()}},[]); return <div className="modal-overlay"><section ref={ref} className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="modal-heading"><h2 id="dialog-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Tutup"><X /></button></div>{children}</section></div>; }
function UnitDialog({ line, onPick, onClose }: { line:CartLine; onPick:(u:Unit)=>void; onClose:()=>void }) { return <Modal title="Pilih satuan dan harga" onClose={onClose}><div className="option-list">{line.product.units.map((unit,index) => <button key={unit.name} data-autofocus={index===0?'true':undefined} onClick={() => onPick(unit)}><span><strong>{unit.name}</strong><small>Isi {unit.multiplier} satuan dasar</small></span><strong>{money.format(unit.price)}</strong>{unit.name === line.unit.name && <Check />}</button>)}</div></Modal>; }
function CustomerDialog({ onPick, onClose }: { onPick:(c:Customer)=>void; onClose:()=>void }) { const [customers,setCustomers]=useState<Customer[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [retry,setRetry]=useState(0); useEffect(()=>{let active=true;setLoading(true);setError('');const timer=setTimeout(()=>listCustomers(q).then(data=>{if(active)setCustomers(data)}).catch(err=>{if(active){setCustomers([]);setError(err instanceof Error?err.message:'Pelanggan gagal dimuat')}}).finally(()=>{if(active)setLoading(false)}),100);return()=>{active=false;clearTimeout(timer)}},[q,retry]); return <Modal title="Pilih pelanggan" onClose={onClose}><label className="search-box"><Search/><span className="sr-only">Cari pelanggan</span><input data-autofocus="true" value={q} onChange={e=>setQ(e.target.value)} placeholder="Nama atau kode pelanggan…"/></label>{loading?<div className="empty-state" role="status">Memuat pelanggan…</div>:error?<div className="inline-recovery" role="alert"><span>{error}</span><button className="button secondary" onClick={()=>setRetry(v=>v+1)}>Coba lagi</button></div>:<div className="option-list">{customers.map(c=><button key={c.id} onClick={()=>onPick(c)}><span><strong>{c.name}</strong><small>{c.code}{c.phone ? ` · ${c.phone}`:''}</small></span><span className="status">{c.tier}</span></button>)}{!customers.length&&<div className="empty-state">Pelanggan tidak ditemukan.</div>}</div>}</Modal>; }
function HeldDialog({ sales,onPick,onClose }:{sales:HeldSale[];onPick:(s:HeldSale)=>void;onClose:()=>void}) { return <Modal title="Transaksi ditahan" onClose={onClose}>{!sales.length?<div className="empty-state">Tidak ada transaksi yang ditahan.</div>:<div className="option-list">{sales.map(s=><button key={s.id} onClick={()=>onPick(s)}><span><strong>{s.reference}</strong><small>{s.customer.name} · {s.lines.length} baris · <Clock3/> {new Date(s.heldAt).toLocaleTimeString('id-ID')}</small></span><strong>{money.format(s.lines.reduce((a,l)=>a+l.qty*l.unit.price-l.discount,0))}</strong></button>)}</div>}</Modal>; }
function PaymentDialog({ customer,cart,total,onClose,onDone }:{customer:Customer;cart:CartLine[];total:number;onClose:()=>void;onDone:(invoice:string,printFailed:boolean)=>void}) { const [paid,setPaid]=useState(total); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const idempotencyKey=useRef(crypto.randomUUID()); async function submit(){if(paid<total)return setError('Uang diterima kurang dari total belanja.');if(saving)return;setSaving(true);setError('');try{const payload={customerId:customer.id,lines:cart.map(l=>({productId:l.product.id,unit:l.unit.name,qty:l.qty,price:l.unit.price,discount:l.discount})),paid,idempotencyKey:idempotencyKey.current};const profile=await getStoreProfile();const result=await submitCheckout(payload,{customer,lines:cart,paid,total},{save:completeSale,print:r=>printReceipt(r,profile)});onDone(result.invoice,result.printFailed)}catch(e){setError(e instanceof Error?e.message:'Transaksi gagal disimpan');setSaving(false)}} return <Modal title="Pembayaran" onClose={onClose}><div className="payment-total"><span>Total pembayaran</span><strong>{money.format(total)}</strong></div><label>Uang diterima<input data-autofocus="true" className="money-input" type="number" min={total} value={paid} onChange={e=>setPaid(Number(e.target.value))} onFocus={e=>e.currentTarget.select()} /></label><div className="quick-cash">{[total,Math.ceil(total/10000)*10000,Math.ceil(total/50000)*50000].filter((v,i,a)=>a.indexOf(v)===i).map(v=><button key={v} onClick={()=>setPaid(v)}>{money.format(v)}</button>)}</div><div className="change"><span>Kembalian</span><strong>{money.format(Math.max(0,paid-total))}</strong></div>{error&&<div className="notice error" role="alert">{error}</div>}<div className="modal-actions"><button className="button secondary" onClick={onClose} disabled={saving}>Batal</button><button className="button primary" onClick={submit} disabled={saving || paid<total}>{saving?'Menyimpan…':<><Printer/>Simpan & cetak</>}</button></div></Modal>; }
